version: '2'
services:
  lb:
    image: rancher/load-balancer-service
    ports:
    - "${public_port}:5601"
    links:
      - kibana5:kibana
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  kibana5:
    restart: always
    tty: true
    image: monlog/kibana:5.5.1
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    stdin_open: true
    external_links:
    - ${elasticsearch_source}:elasticsearch
    tty: true
    labels:
      io.rancher.container.hostname_override: container_name