.catalog:
  name: "Kibana"
  version: "5.5.1-rancher1"
  description: "Kibana: Explore & Visualize Your Data"
  questions:
    - variable: "elasticsearch_source"
      description: "Link to elasticsearch service or stack/service"
      label: "Elasticsearch source"
      type: "service"
      required: true
      default: "es-cluster/es-client"
    - variable: "public_port"
      label: "Public Port"
      description: "Unique public port for Kibana"
      type: "int"
      default: 80
      required: true