name: ASEAN Monitoring
version: v0.1.0
category: Infrastructure Services
description: Monitoring infra services for ASEAN
labels:
  io.rancher.orchestration.supported: 'cattle,mesos,swarm,kubernetes'
